import type { Plugin, ResolvedConfig } from 'vite';
import fs from 'node:fs';
import path from 'node:path';

interface IServicePayload {
  services: Record<string, unknown>;
}

/**
 * Vite plugin that exposes a `/api/services` endpoint during development
 * to write service modifications directly to the ServicesList file.
 */
export function servicesWriterPlugin(): Plugin {
  let config: ResolvedConfig;

  return {
    name: 'services-writer',
    configResolved(resolved) {
      config = resolved;
    },
    configureServer(server) {
      server.middlewares.use('/api/services', async (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end(JSON.stringify({ error: 'Method not allowed' }));
          return;
        }

        try {
          const chunks: Buffer[] = [];
          for await (const chunk of req) {
            chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
          }
          const body = JSON.parse(Buffer.concat(chunks).toString()) as IServicePayload;

          if (!body.services || typeof body.services !== 'object') {
            res.statusCode = 400;
            res.end(JSON.stringify({ error: 'Invalid payload' }));
            return;
          }

          const success = writeServicesFile(config.root, body.services);
          if (success) {
            // Force full reload to re-evaluate the module
            server.ws.send({ type: 'full-reload', path: '*' });
            res.statusCode = 200;
            res.end(JSON.stringify({ ok: true }));
          } else {
            res.statusCode = 500;
            res.end(JSON.stringify({ error: 'Failed to write file' }));
          }
        } catch (err) {
          console.error('[services-writer] Error:', err);
          res.statusCode = 500;
          res.end(JSON.stringify({ error: String(err) }));
        }
      });
    },
  };
}

function writeServicesFile(root: string, services: Record<string, unknown>): boolean {
  try {
    const servicesPath = path.resolve(
      root,
      'src/features/CommandPalette/utils/ServicesList/index.ts',
    );

    const entries: string[] = [];

    for (const [key, svc] of Object.entries(services)) {
      const service = svc as Record<string, unknown>;
      const iconInfo = service.icon as Record<string, unknown> | undefined;
      const svcStyle = service.style as Record<string, string> | undefined;
      const svcUrl = service.url as Record<string, string> | undefined;

      const iconName = iconInfo?.icon && typeof iconInfo.icon === 'string'
        ? iconInfo.icon
        : 'FaGlobe';

      const iconType = (iconInfo?.type as string) || 'react-icons';

      const styleLines: string[] = [];
      if (svcStyle?.backgroundColor) {
        styleLines.push(`      backgroundColor: "${svcStyle.backgroundColor}",`);
      }
      if (svcStyle?.backgroundImage) {
        styleLines.push(`      backgroundImage: "${svcStyle.backgroundImage}",`);
      }
      if (svcStyle?.color) {
        styleLines.push(`      color: "${svcStyle.color}",`);
      }

      entries.push(`  ${key}: {
    name: "${(service.name as string) || key}",
    url: {
      home: "${svcUrl?.home || ''}",
    },
    icon: {
      icon: ${iconName},
      type: "${iconType}",
    },
    style: {
${styleLines.join('\n')}
    },
  },`);
    }

    // Detect which icons are used to generate proper imports
    const usedIcons = new Set<string>();
    for (const [_, svc] of Object.entries(services)) {
      const iconInfo = (svc as Record<string, unknown>)?.icon as Record<string, unknown> | undefined;
      if (iconInfo?.icon && typeof iconInfo.icon === 'string') {
        usedIcons.add(iconInfo.icon);
      }
    }

    // Simple heuristic for icon imports — fa icons, si icons, etc
    const faIcons = new Set<string>();
    const siIcons = new Set<string>();
    const otherIcons: string[] = [];
    for (const name of usedIcons) {
      if (name.startsWith('Fa')) faIcons.add(name);
      else if (name.startsWith('Si')) siIcons.add(name);
      else if (name.startsWith('Io') || name.startsWith('Md') || name.startsWith('Pi') || name.startsWith('Rx') || name.startsWith('Tb')) otherIcons.push(name);
    }

    const importLines: string[] = [];
    if (faIcons.size > 0) {
      importLines.push(`import { ${Array.from(faIcons).sort().join(', ')} } from "react-icons/fa";`);
    }
    if (siIcons.size > 0) {
      importLines.push(`import { ${Array.from(siIcons).sort().join(', ')} } from "react-icons/si";`);
    }

    const header = `// Auto-generated by Settings panel
// Edit via the Settings panel or manually update this file.
${importLines.join('\n')}
import type { IServicesList } from "@/types/Service";

export const ServicesList = {`;

    const footer = `} as IServicesList;`;

    const content = `${header}
${entries.join('\n')}
${footer}
`;

    fs.writeFileSync(servicesPath, content, 'utf-8');
    return true;
  } catch (err) {
    console.error('[services-writer] Write failed:', err);
    return false;
  }
}
